name: Edit Opportunity (Not Supported)
description: "⚠️ Editing is not supported. To update a listing: close it and re-add with corrected details."
title: "Edit Opportunity"
labels: ["edit_opportunity"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Editing is not currently supported via issues.

        To update an existing listing, please:
        1. Open a **Close Opportunity** issue to remove the old listing
        2. Open a new **Add Opportunity** issue with the corrected details

        This ensures data integrity. Thank you for understanding!
