name: Edit Opportunity
description: Request to edit an existing opportunity listing
title: "Edit Opportunity"
labels: ["edit_opportunity"]
body:
  - type: markdown
    attributes:
      value: |
        ## Edit Opportunity Request
        Use this form to request changes to an existing opportunity listing.

  - type: input
    id: url
    attributes:
      label: URL of the Opportunity to Edit
      description: The application link of the opportunity you want to edit
      placeholder: ex. https://careers.google.com/students/step
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: What changes need to be made?
      description: |
        Describe what information needs to be updated.
        Be specific about the current value and what it should be changed to.
      placeholder: |
        - Location should be updated from "Menlo Park, CA" to "Menlo Park, CA | Remote"
        - The application is now closed
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Changes (Optional)
      description: Why do these changes need to be made?
      placeholder: The company updated their job posting to include remote options...
    validations:
      required: false
